Repository Seagate/seagate-tools, pull requests merged in 2022-08, with the labels that each got.

#579 CORTX-17897: Changed docker to docker-ce for build information
  performance/PerfPro/VERSION
  performance/PerfPro/roles/benchmark/files/PerfProBenchmark/s3bench/s3bench_summary.py
  performance/PerfPro/roles/benchmark/tasks/read_docker.yml
Labels: cla-signed

#580 CORTX-33854: Added supports for rocky linux LC setup
  performance/PerfLine/VERSION
  performance/PerfLine/roles/perfline_setup/tasks/taskq.yml
Labels: cla-signed

#581 Remove example node and clients from config.yml
  performance/PerfPro/roles/benchmark/vars/config.yml
Labels: cla-signed

#582 CORTX-33075: [Perf-Sanity] Fix /all not displaying data on fresh load
  dashboards/perf-rest/rest_app/sanity.py
  dashboards/perf-rest/setup.py
  dashboards/superperf/VERSION
Labels: cla-signed, SuperPerf, Perf-Rest, Status: Waiting to be Reviewed

#583 Update config.yml with automated clients, nodes formatting
  performance/PerfPro/VERSION
  performance/PerfPro/roles/benchmark/vars/config.yml
Labels: cla-signed, Status: Waiting to be Reviewed

#584 CORTX-30463: Make use of static endpoint with static NodePorts
  performance/PerfLine/VERSION
  performance/PerfLine/roles/perfline_setup/files/wrapper/scripts/LC/rgw_artifacts.sh
  performance/PerfLine/roles/perfline_setup/files/wrapper/scripts/LC/worker_polymorphic_funcs.sh
  performance/PerfLine/roles/perfline_setup/files/wrapper/scripts/s3bench_run.sh
  performance/PerfLine/roles/perfline_setup/files/wrapper/workload/jenkins/mini_workload/m0_kv_workload.yaml
  performance/PerfLine/roles/perfline_setup/files/wrapper/workload/jenkins/mini_workload/m0crate_workload.yaml
  performance/PerfLine/roles/perfline_setup/files/wrapper/workload/jenkins/mini_workload/s3bench_workload.yaml
  performance/PerfLine/roles/perfline_setup/files/wrapper/workload/jenkins/standard/tescase_200clients500000samples64K-mkfs.yaml
  performance/PerfLine/roles/perfline_setup/files/wrapper/workload/jenkins/standard/testcase_200clients10000samples1G-mkfs.yaml
  performance/PerfLine/roles/perfline_setup/files/wrapper/workload/jenkins/standard/testcase_200clients40000samples128M-mkfs.yaml
  performance/PerfLine/roles/perfline_setup/files/wrapper/workload/jenkins/standard/testcase_200clients40000samples16M-mkfs.yaml
  performance/PerfLine/roles/perfline_setup/files/wrapper/workload/jenkins/standard/testcase_200clients500000samples1M-mkfs.yaml
  performance/PerfLine/roles/perfline_setup/files/wrapper/workload/jenkins/standard/testcase_200clients500000samples4K-mkfs.yaml
  performance/PerfLine/roles/perfline_setup/files/wrapper/workload/jenkins/standard/testcase_multipart_samples4K_64K_1M_16M_120M_1G-without-mkfs.yaml
Labels: cla-signed, PerfLine
