Repository Seagate/seagate-tools, pull requests merged in 2022-07, with the labels that each got.

#559 Update README.md
  README.md
Labels: cla-signed

#560 CORTX-30469: Support Multi-pod configuration for report artifacts
  performance/PerfLine/VERSION
  performance/PerfLine/roles/perfline_setup/files/wrapper/scripts/LC/conf_customization/update_configs.sh
  performance/PerfLine/roles/perfline_setup/files/wrapper/scripts/LC/rgw_artifacts.sh
  performance/PerfLine/roles/perfline_setup/files/wrapper/scripts/LC/run_m0crate
  performance/PerfLine/roles/perfline_setup/files/wrapper/scripts/LC/s3srv_artifacts.sh
  performance/PerfLine/roles/perfline_setup/files/wrapper/scripts/LC/worker_polymorphic_funcs.sh
Labels: cla-signed

#561 Update pull_request_template.md
  .github/pull_request_template.md
Labels: cla-signed

#562 CORTX-30464: Add DPS features into PerfLine
  performance/PerfLine/README.md
  performance/PerfLine/VERSION
  performance/PerfLine/ansible.cfg
  performance/PerfLine/env/README.md
  performance/PerfLine/env/input.yaml
  performance/PerfLine/env/install_dev_env.sh
  performance/PerfLine/readme.md
  performance/PerfLine/roles/perfline_setup/files/perfline.conf
  performance/PerfLine/roles/perfline_setup/files/wrapper/continue_task.sh
  performance/PerfLine/roles/perfline_setup/files/wrapper/core/tasks.py
  performance/PerfLine/roles/perfline_setup/files/wrapper/core/validator.py
  performance/PerfLine/roles/perfline_setup/files/wrapper/scripts/LC/worker_polymorphic_funcs.sh
  performance/PerfLine/roles/perfline_setup/files/wrapper/scripts/common_wait.sh
  performance/PerfLine/roles/perfline_setup/files/wrapper/scripts/worker.sh
  performance/PerfLine/roles/perfline_setup/files/wrapper/wait_task.sh
  performance/PerfLine/roles/perfline_setup/tasks/pre-req_perfline.yml
  performance/PerfLine/roles/perfline_setup/tasks/taskq.yml
Labels: cla-signed, PerfLine

#564 Update .alexignore
  .alexignore
Labels: cla-signed

#565 CORTX-33500: [SuperPerf][Perf-Rest] Support for baseline wrt infra type
  dashboards/perf-rest/rest_app/sanity.py
  dashboards/perf-rest/rest_app/sanityapi.py
  dashboards/perf-rest/setup.py
  dashboards/superperf/VERSION
  performance/PerfPro/readme.md
Labels: cla-signed, SuperPerf, Perf-Rest

#569 CORTX-33072: Modularization of system monitoring script
  performance/PerfPro/roles/benchmark/files/PerfProBenchmark/modules/common_functions.py
  performance/PerfPro/roles/benchmark/files/PerfProBenchmark/modules/schemas.py
  performance/PerfPro/roles/benchmark/files/PerfProBenchmark/modules/system_monitoring.py
Labels: cla-signed

#573 Rename readme to README
  README.md
  dashboards/cortx-companion/README.md
  dashboards/perf-rest/README.md
  dashboards/superperf/README.md
  performance/PerfPro/README.md
Labels: cla-signed

#574 CORTX-33071: Add Performance results summary table for Perf-Sanity
  performance/PerfPro/VERSION
  performance/PerfPro/roles/benchmark/files/PerfProBenchmark/sanity/sanity_summary.py
  performance/PerfPro/roles/benchmark/tasks/main.yml
Labels: cla-signed

#571 CORTX-33714: Make use of default ssh key for passwordless authentication
  performance/PerfLine/VERSION
  performance/PerfLine/ansible.cfg
  performance/PerfLine/roles/perfline_setup/files/chronometry/addb2db.py
  performance/PerfLine/roles/perfline_setup/files/passwordless_ssh.sh
  performance/PerfLine/roles/perfline_setup/tasks/enable_passwordless.yml
Labels: cla-signed, PerfLine

#576 CORTX-33737: Delegated docker installation from PerfPro Orchestrator to Client1
  performance/PerfPro/VERSION
  performance/PerfPro/roles/benchmark/tasks/main.yml
  performance/PerfPro/roles/benchmark/tasks/read_docker.yml
Labels: cla-signed

#578 CORTX-17895 : Printing Summary tables for S3Bench, HSBench
  performance/PerfPro/VERSION
  performance/PerfPro/roles/benchmark/files/PerfProBenchmark/hsbench/hsbench_summary.py
  performance/PerfPro/roles/benchmark/files/PerfProBenchmark/s3bench/s3bench_summary.py
  performance/PerfPro/roles/benchmark/tasks/main.yml
  performance/PerfPro/roles/benchmark/tasks/prepare_setup.yml
Labels: cla-signed, PerfPro

#577 CORTX-33080: Modularized configuration collection script
  performance/PerfPro/roles/benchmark/files/PerfProBenchmark/modules/add_perfpro_config.py
Labels: cla-signed

#575 CORTX-30462: Added support for m0crate KV workload in PerfLine
  performance/PerfLine/VERSION
  performance/PerfLine/roles/perfline_setup/files/wrapper/core/tasks.py
  performance/PerfLine/roles/perfline_setup/files/wrapper/core/validator.py
  performance/PerfLine/roles/perfline_setup/files/wrapper/scripts/LC/run_m0crate
  performance/PerfLine/roles/perfline_setup/files/wrapper/scripts/LC/worker_polymorphic_funcs.sh
  performance/PerfLine/roles/perfline_setup/files/wrapper/scripts/test_kv.yaml.template
  performance/PerfLine/roles/perfline_setup/files/wrapper/scripts/worker.sh
  performance/PerfLine/roles/perfline_setup/files/wrapper/stat/report_generator/gen_report.py
Labels: cla-signed
